HotelBookingRooms/HotelBookingRooms.Web/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HotelBookingRooms.Web.Controllers
{
    public class ChatController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HotelBookingRooms/HotelBookingRooms.Web/Controllers/HotelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccessLayer.Core.Interfaces.UoW;
using HotelBookingRooms.BLL.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace HotelBookingRooms.Web.Controllers
{
    public class HotelController : BaseController
    {
        public HotelController(IUnitOfWork uow, ILoggerFactory loggerFactory) : base(uow, loggerFactory)
        {
            
        }

        public IActionResult Index()
        {
            var hotels = Uow.Repository<Hotel>().GetRange();
            return View(hotels);
        }

        [HttpGet]
        public IActionResult Create()
        {
            //var hotels = Uow.Repository<Hotel>().GetRange();
            return View(new Hotel());
        }

        [HttpPost]
        public IActionResult Create(Hotel hotel)
        {
            Uow.Repository<Hotel>().Add(hotel);
            Uow.Save();
            return View();
        }

        [HttpPost]
        public IActionResult Create(int Id)
        {
            var deleteHotel = Uow.Repository<Hotel>().Get(Id);
            Uow.Repository<Hotel>().Delete(deleteHotel);
            Uow.Save();
            return RedirectToAction("Index");
        }

        //[HttpPost]
        public IActionResult Delete(int? Id)
        {
            if(Id == null)
            {
                return NotFound();
            }
            var deleteHotel = Uow.Repository<Hotel>().Get((int)Id);
            if(deleteHotel == null)
            {
                return NotFound();
            }
            return View(deleteHotel);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int? Id)
        {
            var deleteHotel = Uow.Repository<Hotel>().Get((int)Id);
            if (deleteHotel == null)
            {
                return NotFound();
            }
            try
            {
                Uow.Repository<Hotel>().Delete(deleteHotel);
                Uow.Save();
                return RedirectToAction("Index");
            }
            catch(Exception)
            {
                return RedirectToAction(nameof(Delete), new { id = Id, saveChangesError = true });
            }
        }

        public IActionResult Edit(int Id, Hotel hotel)
        {
            if(Id != hotel.Id)
            {
                return NotFound();
            }
            if(ModelState.IsValid)
            {
                try
                {
                    var deleteHotel = Uow.Repository<Hotel>().Get(Id);
                    Uow.Repository<Hotel>().Delete(deleteHotel);
                    Uow.Save();
                    return RedirectToAction("Index");
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError("", "Unable to update your database"); // Log Error
                }
            }
            return View(hotel);

        }
    }
}

HotelBookingRooms/HotelBookingRooms.Web/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccessLayer.Core.Interfaces.UoW;
using HotelBookingRooms.BLL.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HotelBookingRooms.ViewModels.RoomVM;
using HotelBookingRooms.Services.Interfaces;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HotelBookingRooms.Web.Controllers
{
    public class RoomController : Controller
    {
        private readonly IHotelService IHotelService;
        private readonly IRoomService IRoomService;
        private readonly IRoomTypeService IRoomTypeService;

        public RoomController(IRoomService IRoomService, IRoomTypeService IRoomTypeService, IHotelService IHotelService)
        {
            this.IRoomService = IRoomService;
            this.IRoomTypeService = IRoomTypeService;
            this.IHotelService = IHotelService;
        }

        public IActionResult Index()
        {
            var rooms = IRoomService.GetRooms();
            return View(rooms);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Hotels = IHotelService.GetHotels().ToList();
            var newRoom = new CreateRoomVM();
            return View(newRoom);
        }

        [HttpPost]
        public IActionResult Create([Bind("RoomNumber, FloorNumber, RoomTypeId, HotelId")] CreateRoomVM room)
        {
            if(IRoomService.AddRoom(room))
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        //[HttpPost]
        public IActionResult Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var deleteRoom = IRoomService.GetRoom((int)Id);
            if (deleteRoom == null)
            {
                return NotFound();
            }
            return View(deleteRoom);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int? Id)
        {
            var deleteRoom = IRoomService.GetRoom((int)Id);
            if (deleteRoom == null)
            {
                return NotFound();
            }
            try
            {
                IRoomService.DeleteRoom((int)Id);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Delete), new { id = Id, saveChangesError = true });
            }
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var room = IRoomService.GetRoom((int)id);

            if (room == null)
            {
                return NotFound();
            }
            
            return View(room);
        }

        [HttpGet, ActionName("Edit")]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = IRoomService.GetRoom((int)id);

            ViewBag.RoomTypes = IRoomTypeService
                .GetRoomTypesForSpecificHotel(room.RoomType.HotelId)
                    .ToList();

            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int? id, [Bind("Id, RoomNumber, FloorNumber, RoomTypeID")] Room room)
        {
            if (id == null)
            {
                return NotFound();
            }

            ViewBag.Error = true;

            if (ModelState.IsValid)
            {
                if (IRoomService.EditRoom((int)id, room) == true)
                {
                    ViewBag.Error = false;
                }
            }

            room = IRoomService.GetRoom((int)id);

            ViewBag.RoomTypes = IRoomTypeService
                .GetRoomTypesForSpecificHotel(room.RoomType.HotelId)
                    .ToList();

            return View(room);
        }

        public JsonResult GetRoomTypesList(int id)
        {
            var RoomTypeList = IRoomTypeService
                                 .GetRoomTypesForSpecificHotel(id)
                                    .ToList();

            RoomTypeList.Insert(0, new RoomType { Id = 0, Name = "Please select roomtype" });
            var selectedList = new SelectList(RoomTypeList, "Id", "Name");
            return Json(selectedList);
        }
    }
}

HotelBookingRooms/HotelBookingRooms.Web/Controllers/RoomTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HotelBookingRooms.BLL.Entities;
using HotelBookingRooms.Services.Interfaces;
using HotelBookingRooms.ViewModels;
using HotelBookingRooms.ViewModels.RoomTypeVM;
using HotelBookingRooms.ViewModels.RoomVM;
using Microsoft.AspNetCore.Mvc;

namespace HotelBookingRooms.Web.Controllers
{
    public class RoomTypeController : Controller
    {
        private readonly IHotelService IHotelService;
        private readonly IRoomService IRoomService;
        private readonly IRoomTypeService IRoomTypeService;

        public RoomTypeController(IRoomService IRoomService, IRoomTypeService IRoomTypeService, IHotelService IHotelService)
        {
            this.IRoomService = IRoomService;
            this.IRoomTypeService = IRoomTypeService;
            this.IHotelService = IHotelService;
        }

        public IActionResult Index()
        {
            var roomTypes = IRoomTypeService.GetRoomTypes().ToList();
            return View(roomTypes);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Hotels = IHotelService.GetHotels().ToList();
            return View(new CreateRoomTypeVM());
        }

        [HttpPost]
        public IActionResult Create(CreateRoomTypeVM roomType)
        {

            RoomType type = new RoomType()
            {
                HotelId = roomType.HotelId,
                Name = roomType.Name,
                Area = roomType.Area,
                PriceSeasonNumber = Convert.ToDecimal(roomType.PriceStandardNumber),
                PriceStandardNumber = Convert.ToDecimal(roomType.PriceStandardNumber),
                NumberOfBeds = roomType.NumberOfBeds,
                NumberOfPeople = roomType.NumberOfPeople,
                Description = roomType.Description,

            };

            if (IRoomTypeService.AddRoomType(type))
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Create");
        }

        //[HttpPost]
        public IActionResult Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var roomType = IRoomTypeService.GetRoomType((int)Id);
            if (roomType == null)
            {
                return NotFound();
            }
            return View(roomType);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int? Id)
        {
            var roomType = IRoomTypeService.GetRoomType((int)Id);
            if (roomType == null)
            {
                return NotFound();
            }
            try
            {
                IRoomTypeService.DeleteRoomType((int)Id);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Delete), new { id = Id, saveChangesError = true });
            }
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = IRoomTypeService.GetRoomType((int)id);

            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        [HttpGet, ActionName("Edit")]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ViewBag.Hotels = IHotelService.GetHotels().ToList();

            var roomType = IRoomTypeService.GetRoomType((int)id);

            EditRoomTypeVM editRoomTypeVM = new EditRoomTypeVM()
            {
                HotelId = roomType.HotelId,
                Name = roomType.Name,
                Area = roomType.Area,
                PriceSeasonNumber = roomType.PriceStandardNumber,
                PriceStandardNumber = roomType.PriceStandardNumber,
                NumberOfBeds = roomType.NumberOfBeds,
                NumberOfPeople = roomType.NumberOfPeople,
                Description = roomType.Description,

            };

            if (roomType == null)
            {
                return NotFound();
            }

            return View(editRoomTypeVM);
        }

        [HttpPost, ActionName("Edit")]
        public IActionResult Edit(int? id, EditRoomTypeVM editRoomTypeVM)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (IRoomTypeService.EditRoomType((int)id, editRoomTypeVM) == false)
                {
                    ViewBag.Error = true;
                    return View(editRoomTypeVM);
                }
            }

            var roomType = IRoomTypeService.GetRoomType((int)id);

            EditRoomTypeVM vm = new EditRoomTypeVM()
            {
                HotelId = roomType.HotelId,
                Name = roomType.Name,
                Area = roomType.Area,
                PriceSeasonNumber = roomType.PriceStandardNumber,
                PriceStandardNumber = roomType.PriceStandardNumber,
                NumberOfBeds = roomType.NumberOfBeds,
                NumberOfPeople = roomType.NumberOfPeople,
                Description = roomType.Description,

            };

            ViewBag.Hotels = IHotelService.GetHotels().ToList();
            ViewBag.Error = false;

            return View(vm);
        }
    }
}

HotelBookingRooms/HotelBookingRooms.Web/Views/Shared/RoomSummary.cshtml
@model HotelBookingRooms.BLL.Entities.Room


<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.RoomType.Name
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.RoomType.PriceStandardNumber.ToString("c")</small>
            </span>
        </h4>
</div>
    <form id="@Model.Id" asp-action="AddToCart"
          asp-controller="Cart" method="post">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.PathAndQuery()"/>
               @*value="@ViewContext.HttpContext.Request.PathAndQuery()"/>*@
        <span class="card-text" p-1">
            @Model.RoomType.Description
            <button type="submit"
                    class="btn btn-success btn-sm pull-right" style="float:right" >
                Dodaj do koszyka
            </button>
        </span>
    </form>
</div>

HotelBookingRooms/HotelBookingRooms.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Setup Solution</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Setup Solution</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Hotel" asp-action="Index">Hotels</a></li>
                    @if (User.Identity.IsAuthenticated == true)
                    {
                    <li><a asp-area="" asp-controller="Reservation" asp-action="Index">Reservations</a></li>
                    }
                    @if (User.Identity.IsAuthenticated == true)
                    {
                    <li><a asp-area="" asp-controller="Reservation" asp-action="GetUserReservation">YourReservation</a></li>
                    }
                <li><a asp-area="" asp-controller="Room" asp-action="Index">Rooms</a></li>
                <li><a asp-area="" asp-controller="Reservation" asp-action="SearchRoom">SearchRoom</a></li>
                <li><a asp-area="" asp-controller="RoomType" asp-action="Index">Room types</a></li>
                <li><a asp-area="" asp-controller="Chat" asp-action="Index">Chat</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Setup Solution</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>